CREATE DATABASE IF NOT EXISTS th_system DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'th_user'@'localhost' IDENTIFIED BY 'REPLACE_ME_PASSWORD';
GRANT ALL ON th_system.* TO 'th_user'@'localhost';
CREATE USER IF NOT EXISTS 'th_user'@'%' IDENTIFIED BY 'REPLACE_ME_PASSWORD';
GRANT ALL ON th_system.* TO 'th_user'@'%';
FLUSH PRIVILEGES;