SET @has_user_id := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'user_id');
SET @has_name := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND COLUMN_NAME = 'name');
SET @has_pk_id := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND CONSTRAINT_NAME = 'PRIMARY' AND COLUMN_NAME = 'id');

DO 0;

ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users DROP COLUMN user_id;
ALTER TABLE users ADD PRIMARY KEY (id);

ALTER TABLE users DROP COLUMN name;

SET @has_idx_user := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND INDEX_NAME = 'uniq_username');
SET @has_idx_wecom := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' AND INDEX_NAME = 'uniq_wecom');

ALTER TABLE users ADD UNIQUE KEY uniq_username (username);
ALTER TABLE users ADD UNIQUE KEY uniq_wecom (wecom_user_id);