CREATE TABLE IF NOT EXISTS `import_tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(36) NOT NULL,
  `batch_id` VARCHAR(36) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `stored_path` VARCHAR(512) NULL,
  `file_url` VARCHAR(512) NULL,
  `status` VARCHAR(20) NOT NULL,
  `records` INT UNSIGNED NOT NULL DEFAULT 0,
  `skipped` INT UNSIGNED NOT NULL DEFAULT 0,
  `imported` INT UNSIGNED NOT NULL DEFAULT 0,
  `duplicates` INT UNSIGNED NOT NULL DEFAULT 0,
  `conflicts` INT UNSIGNED NOT NULL DEFAULT 0,
  `anomalies_total` INT UNSIGNED NOT NULL DEFAULT 0,
  `anomalies_processed` INT UNSIGNED NOT NULL DEFAULT 0,
  `skip_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `overwrite_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `auto_resolved` INT UNSIGNED NOT NULL DEFAULT 0,
  `manual_resolved` INT UNSIGNED NOT NULL DEFAULT 0,
  `message` TEXT NULL,
  `progress_last_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_import_tasks_task_id` (`task_id`),
  KEY `idx_import_tasks_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;